---
sidebar: sidebar
permalink: reference_new_occm.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.
---

= What's new in Cloud Backup
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.

tag::whats-new[]
== 28 Nov 2021

=== Support for Kubernetes clusters

Now you can back up persistent volumes from your Kubernetes clusters to Amazon S3.

If your EKS cluster has NetApp Astra Trident installed, and it is using Cloud Volumes ONTAP for AWS as backend storage for the cluster, then you can back up and restore volumes to and from Amazon S3. link:task_backup_kubernetes_to_s3.html[Go here for details].

=== Support for DP volumes with SVM-DR

Cloud Backup now supports creating backups of DP volumes that exist on the target ONTAP system in an SVM-DR relationship. There are a few restrictions, so see link:concept_backup_to_cloud.html#limitations[the limitations] for details.

== 5 Nov 2021

=== Support for private endpoints

When restoring a volume to an on-premises ONTAP system from a backup file that resides on Amazon S3 or Azure Blob, now you can select a private endpoint that connects to your on-prem system privately and securely.

=== Tiering to archival storage

Now you can tier older backup files to archival storage after a certain number of days to save costs.

If your cluster is running ONTAP 9.10.1 or greater, and you are using AWS or Azure cloud storage, you can enable tiering of backups to archival storage. See more information about link:reference-aws-backup-tiers.html[AWS S3 archival storage classes] and link:reference-azure-backup-tiers.html[Azure Blob archival access tiers].

=== Licensing update

BYOL licensing for Cloud Backup has moved from the Cloud Backup Licenses tab to the Data Services Licenses tab in the Cloud Manager Digital Wallet.

== 2 Sept 2021

=== On-demand backups

Now you can create an on-demand backup at any time to capture the current state of a volume. This is useful if important changes have been made to a volume and you don’t want to wait for the next scheduled backup to protect that data.

link:task_managing_backups.html#creating-a-manual-volume-backup-at-any-time[See how to create an on-demand backup].

=== Private Interface Endpoints

When configuring backups to Amazon S3 from an on-premises ONTAP system, now you can define a connection to a Private Interface Endpoint in the activation wizard. This allows you to use a network interface that connects your on-prem system privately and securely to a service powered by AWS PrivateLink. link:task_backup_onprem_to_aws.html#preparing-amazon-s3-for-backups[See details about this option].

=== Support for customer-managed keys

For additional security and control, you can choose your own customer-managed keys for data encryption in the activation wizard instead of using the default Amazon S3 encryption keys.

This is available when configuring backups from an on-premises ONTAP system or from a Cloud Volumes ONTAP system in AWS.

=== Enhancement for large directories

The restriction of being able to browse a single directory with flat files up to a maximum of 30,000 files has been removed. Now you can restore files from directories that have a larger number of files.
end::whats-new[]

== 2 Aug 2021

Other features
